/*ATTENTION: this file has been automatically generated by a MATLAB script 
 avoid manual changes!*/
#ifndef FILTER_AND_CONTROL_PARAMS_H_
#define FILTER_AND_CONTROL_PARAMS_H_

#define LOOP_PERIOD_MS 10  //[ms] loop period 
#define N_POLES	30	// []total poles of the motor 
#define N_HALL	3	// []number of hall sensors 
#define KT	(float)0.694000 // [Nm/A] torque per Ampere 
#define R_WHEEL	(float)0.100000	// [m]wheel radius 
#define RHO	(float)1.000000	// [] gear reduction ratio 
#define D	(float)0.500000	// [m]distance between the 2 wheels 

// Equilibrium LQR parameters 
#define CTL_BALANCE_XB_GAIN				(float)-9.288012
#define CTL_BALANCE_THETA_P_GAIN		(float)-58.063364
#define CTL_BALANCE_DOT_XB_GAIN			(float)-21.379682
#define CTL_BALANCE_DOT_THETA_P_GAIN	(float)-8.951821

// Second order filter "HPF"
#define HPF_COEF_N0 (float)0.000000
#define HPF_COEF_N1 (float)7.838978
#define HPF_COEF_N2 (float)-7.838978
#define HPF_COEF_D1 (float)-1.562285
#define HPF_COEF_D2 (float)0.641324

// First order filter "INT"
#define INT_COEF_N0 (float)0.000000
#define INT_COEF_N1 (float)0.010000
#define INT_COEF_D1 (float)-1.000000

// First order filter "PID"
#define PID_COEF_N0 (float)2.000000
#define PID_COEF_N1 (float)-1.992381
#define PID_COEF_D1 (float)-1.000000

// Second order filter "LPF"
#define LPF_COEF_N0 (float)0.000000
#define LPF_COEF_N1 (float)0.821026
#define LPF_COEF_N2 (float)0.094414
#define LPF_COEF_D1 (float)-0.086428
#define LPF_COEF_D2 (float)0.001867


#define COMPLEM_FILT_ALPHA	(float)0.999000
#define COMPLEM_FILT_BETA	(float)0.001000

#define LQR_STEER_DELTA_GAIN	(float)3.051953
#define LQR_STEER_DOT_DELTA_GAIN	(float)2.997545

#define IMU_ACCX_OFFSET	(float)-0.331750
#define IMU_ACCZ_OFFSET	(float)0.377100
#define IMU_GYRO_OFFSET	(float)-0.014000

// Backlash compensator
#define DIST_TORQUE_AMPL	(float)0.000000
#define DIST_TORQUE_OMEGA	(float)1884.955592
// Second order filter "NOTCH"
#define NOTCH_COEF_N0 (float)1.000000
#define NOTCH_COEF_N1 (float)0.000045
#define NOTCH_COEF_N2 (float)0.000004
#define NOTCH_COEF_D1 (float)0.000049
#define NOTCH_COEF_D2 (float)0.000000

#endif // FILTER_AND_CONTROL_PARAMS_H_
